info:
  app:
    name: "x-boot-web"
    description: "x-boot-web"
  build:
    groupId: "cn.wind.xboot"
    artifact: "x-boot-web"
    version: "1.0.0-SNAPSHOT"
server:
  ip: 127.0.0.1
  port: 8899
spring:
  application:
    name: x-boot-web
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/xboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000 #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      timeBetweenEvictionRunsMillis: 60000 #有两个含义：1) Destroy线程会检测连接的间隔时间2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      minEvictableIdleTimeMillis: 300000 #连接保持空闲而不被驱逐的最小时间
      validationQuery: SELECT 1 FROM DUAL #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      testWhileIdle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testOnBorrow: false #请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      poolPreparedStatements: false #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      maxPoolPreparedStatementPerConnectionSize: -1 #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      filters: stat,wall,slf4j
  # cache
  cache:
    type: redis
  # Redis
  redis:
    host: 127.0.0.1
    #password:
    # 数据库索引 默认0
    #database: 0
    port: 6379
    #timeout: 3000
  # Elasticsearch
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 5Mb
      max-request-size: 5Mb
  freemarker:
    cache: false
    request-context-attribute: request
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      output_encoding: UTF-8
      locale: zh_CN
      number_format: 0.##########
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:s
      classic_compatible: true
      template_exception_handler: ignore
  messages:
    basename: i18n/messages,cn.wind.auth.i18n/messages,org.springframework.security/messages
  mail:
    host: smtp.magicsoft.me
    username: xukk@magicsoft.me
    password: Xukk5621474
    properties:
      mail:
        smtp:
          auth: true
          timeout: 2500
  upload:
    freeRoot: D://temp/free/upload/
    authRoot: D://temp/upload/
#  boot:
#    admin:
#      ui:
#        cache:
#          no-cache: true
#      client:
#        url: http://localhost:8899/admin
#        username: ${spring.security.user.name}
#        password: ${spring.security.user.password}
#        instance:
#          metadata:
#            user.name: ${spring.security.user.name}
#            user.password: ${spring.security.user.password}
#      context-path: /admin
  jmx:
    default-domain: ${spring.application.name}
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/mapper/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.wind.db.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    meta-object-handler: cn.wind.db.handler.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8899/job
    executor:
      appname: xxl-job-executor-app
      ip: ${server.ip}
      port: 9988
      logpath: log/${spring.application.name}/jobhandler
      logretentiondays: -1
    accessToken:


xboot:
  dozer:
    basename: mapping/GlobalMapping.xml
 # 需要授权url
  authenticatedUrl:
    - /api/**
    - /user/**
    - /permission/**
    - /role/**
    - /log/**
    - /upload/info
    - /upload/file
    - /email/**
    - /sms/**
    - /push/**
    - /oauth/logout
    - /notice/**
  # 忽略鉴权url
  ignoredUrl:
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /webjars/**
    - /job/**
    - /free/upload/**
    - /upload/**
    - /favicon.ico
    - /oauth/login
    - /admin/**
    - /actuator/**
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  alioss:
    end-point: http://oss-cn-shanghai.aliyuncs.com
    access-keyId: LTAIUg3wkXF7q4Bf
    access-key-secret: 6jDimXrKDg73moXvDoFlZCbnv5jldt
    bucket: chedai
# Swagger界面内容配置
swagger:
  title: XBoot API接口文档
  description: XBoot Api Documentation
  version: 1.0.0
  termsOfServiceUrl: https://blog.csdn.net/jutudi
  contact:
    name: Xukk
    url: https://blog.csdn.net/jutudi
    email:  xukk@magicsoft.me

logging:
  level:
    root: warn
  path: log/${spring.application.name}/

